### ISSUE TITLE
Inconvenient user workflow for deployment creating/editing

### ISSUE THREAD

**Issue by vshipb** [AltisourceLabs/ecloudmanager#16]
For example: 
As a user I need to add a recipe to VM's run list in the Application Deployment. Currently in Deployment Portal it's not possible at all, and I have to perform following steps:
1. Undeploy this deployment
2. Create Recipe entity if missing
3. Add this Recipe to VMTemplate's runlist
4. Create new ApplicationDeployment from ApplicationTemplate 
5. Fill all constraint fields on entire deployment once again. 
6. Deploy newly created/filled ApplicationDeployment

**Comment by vshipb** [comment]
One possible(?) solution is Recipe/VMTemplate/ApplicationTemplate versioning implementation,  but this solution seems too complicated and not the best one from the end-user point of view.

**Comment by vshipb** [comment]
I think following solution would be much better:
1. Support fully-functional ApplicationDeployment object editing, The user should be able to create new ApplicationDeployment, add new VMs, ProducedServices, other components directly to this object.  
2. Implement import-export support for any(?) ApplicationDeployment child objects, with possibilty to exclude some information from import/export (e.g. exclude Infrastructure-related information).. 
   This functionality will allow deployment parts reuse and should replace current App/VMTemplates functionality. 
3.  Rename ApplicationDeployment to Blueprint, remove APP/VM/...Templates functionality from DeploymentPortal

**Comment by ovkhasch** [comment]
Next steps:

We need an ability to reuse the deployment components (component means service/component group/VM template/recipe in this context). One possibility could be implementing a copy UI in a form of "importing". 

The highlights:
1. The deployment is self-containing. It includes everything: from services to vm templates and recipes.
1a. This means that each deployment will have its own set of VM templates and recipes. And we move the UI for VM templates/recipes editing inside the deployment editor.
2. The deployment editor UI has a number of places where we create deployment components - like adding a service, backend, VM template or recipe to it. In these places we provide an option to import such component from another deployment instead of creating a new one. It will copy a component from that deployment.
3. After selecting "import" the user should be presented with the UI which helps to effectively search for a component through the existing deployments.
4. An ability to create a copy of a component with a new name inside a single deployment could be useful too. The usecase is - copy and then slightly modify a component.
5. Component names should be prefixed with the deployment name in the UI where it is needed to avoid confusion. We need to maintain name uniqueness when creating or importing components.
6. There should be a common repository of the components (we have this for the VM templates and recipes right now). These components can be imported (copy) into the deployments and then edited as needed.

**Comment by vshipb** [comment]
Can we create a copy of a deployment with a new name?

**Comment by ovkhasch** [comment]
Copying of a whole deployment is not implemented yet, but will be ready soon

**Comment by ovkhasch** [comment]
This feature is complete
